FROM public.ecr.aws/lambda/python:3.8

WORKDIR /code

COPY ./app /code/app

COPY ./requirements.txt /code/requirements.txt

COPY ./.env /code/.env

RUN pip install -r /code/requirements.txt

CMD ["code.app.main.handler"]